import numpy as np
import pandas as pd
import matplotlib.pyplot as plt

df = pd.read_csv("C:\ProjectDA\hotel_bookings.csv")

print(df.head())
print(df.shape)
print(df.info())
print(df.describe())
print(df.isnull().sum())
print(df.duplicated().sum())

total_bookings = len(df)
canceled_bookings = (df["Booking_Status"] == "Canceled").sum()
not_canceled_bookings = (df["Booking_Status"] == "Not Canceled").sum()
cancellation_rate = canceled_bookings / total_bookings * 100

average_adr = df["ADR"].mean()
median_adr = df["ADR"].median()
highest_adr = df["ADR"].max()
lowest_adr = df["ADR"].min()
average_lead_time = df["Lead_Time"].mean()

hotel_count = df["Hotel"].value_counts()
hotel_cancellation = df.groupby("Hotel")["Booking_Status"].apply(
    lambda x: (x == "Canceled").mean() * 100
).sort_values(ascending=False)

monthly_bookings = df["Arrival_Month"].value_counts()
customer_type_count = df["Customer_Type"].value_counts()
market_segment_count = df["Market_Segment"].value_counts()
meal_count = df["Meal"].value_counts()
hotel_adr = df.groupby("Hotel")["ADR"].mean().sort_values(ascending=False)

print("Total Bookings:", total_bookings)
print("Canceled Bookings:", canceled_bookings)
print("Not Canceled Bookings:", not_canceled_bookings)
print("Cancellation Rate:", round(cancellation_rate, 2), "%")
print("Average ADR:", round(average_adr, 2))
print("Median ADR:", round(median_adr, 2))
print("Highest ADR:", highest_adr)
print("Lowest ADR:", lowest_adr)
print("Average Lead Time:", round(average_lead_time, 2), "days")
print("Most Booked Hotel:", hotel_count.idxmax())
print("Highest Cancellation Hotel:", hotel_cancellation.idxmax())
print("Most Common Customer Type:", customer_type_count.idxmax())
print("Most Common Market Segment:", market_segment_count.idxmax())
print("Most Popular Meal:", meal_count.idxmax())

plt.figure(figsize=(8, 5))
hotel_count.plot(kind="bar")
plt.title("Hotel Type Distribution")
plt.xlabel("Hotel Type")
plt.ylabel("Number of Bookings")
plt.xticks(rotation=0)
plt.tight_layout()
plt.show()

plt.figure(figsize=(8, 5))
df["Booking_Status"].value_counts().plot(kind="bar")
plt.title("Booking Status Distribution")
plt.xlabel("Booking Status")
plt.ylabel("Number of Bookings")
plt.xticks(rotation=0)
plt.tight_layout()
plt.show()

plt.figure(figsize=(9, 5))
monthly_bookings.plot(kind="bar")
plt.title("Monthly Booking Trends")
plt.xlabel("Arrival Month")
plt.ylabel("Number of Bookings")
plt.xticks(rotation=0)
plt.tight_layout()
plt.show()

plt.figure(figsize=(8, 5))
hotel_cancellation.plot(kind="bar")
plt.title("Cancellation Rate by Hotel Type")
plt.xlabel("Hotel Type")
plt.ylabel("Cancellation Rate (%)")
plt.xticks(rotation=0)
plt.tight_layout()
plt.show()

plt.figure(figsize=(8, 5))
hotel_adr.plot(kind="bar")
plt.title("Average Daily Rate by Hotel Type")
plt.xlabel("Hotel Type")
plt.ylabel("Average ADR")
plt.xticks(rotation=0)
plt.tight_layout()
plt.show()

plt.figure(figsize=(9, 5))
customer_type_count.plot(kind="bar")
plt.title("Bookings by Customer Type")
plt.xlabel("Customer Type")
plt.ylabel("Number of Bookings")
plt.xticks(rotation=45)
plt.tight_layout()
plt.show()

plt.figure(figsize=(10, 5))
market_segment_count.plot(kind="bar")
plt.title("Bookings by Market Segment")
plt.xlabel("Market Segment")
plt.ylabel("Number of Bookings")
plt.xticks(rotation=45)
plt.tight_layout()
plt.show()

plt.figure(figsize=(8, 5))
df["Lead_Time"].plot(kind="hist", bins=10)
plt.title("Lead Time Distribution")
plt.xlabel("Lead Time (Days)")
plt.ylabel("Number of Bookings")
plt.tight_layout()
plt.show()

plt.figure(figsize=(8, 5))
meal_count.plot(kind="bar")
plt.title("Meal Preference Distribution")
plt.xlabel("Meal Type")
plt.ylabel("Number of Bookings")
plt.xticks(rotation=0)
plt.tight_layout()
plt.show()

plt.figure(figsize=(8, 5))
plt.scatter(df["Lead_Time"], df["ADR"])
plt.title("Lead Time vs Average Daily Rate")
plt.xlabel("Lead Time (Days)")
plt.ylabel("ADR")
plt.tight_layout()
plt.show()

print("Hotel Booking Summary:")
print(hotel_count)

print("Cancellation Rate by Hotel:")
print(hotel_cancellation)

print("Average ADR by Hotel:")
print(hotel_adr)

print("Bookings by Customer Type:")
print(customer_type_count)

print("Bookings by Market Segment:")
print(market_segment_count)

print("Bookings by Meal:")
print(meal_count)

print("ADR Range:", highest_adr - lowest_adr)
print("Lead Time Standard Deviation:", round(df["Lead_Time"].std(), 2))
print("ADR Standard Deviation:", round(df["ADR"].std(), 2))